### ISSUE TITLE
to be better

### ISSUE THREAD

**Issue by CCat00** [HeshamMegid/HMSegmentedControl-Swift#1]
Hi,
I'm use your HMSegmentedControl in Object-C is very good, but the swift-version is not good, the swift version can update? I hope you can (e.g. add `UIScrollView`). Thank you.

**Comment by HeshamMegid** [comment]
Hi @Hanwp. I believe you have missed this paragraph in the readme 🙂

> HMSegmentedControl-Swift currently only has a small subset of the features of HMSegmentedControl, and it's not ready for production use yet. Feel free to create issues and submit pull requests to help port over all the features.

**Comment by CCat00** [comment]
ok，thank you.
